//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonGrade
    {
        public int PersonGradeId { get; set; }
        public int Grade { get; set; }
        public int CourseId { get; set; }
        public int PersonId { get; set; }
        public string Comment { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
