//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonGrade
    {
        public int PersonGradeId { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Comment { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
